const actionTypes = {
  nameActions: {
    GET_NAMES_START: 'GET_NAMES_START',
    GET_NAMES_SUCCESS: 'GET_NAMES_SUCCESS',
    GET_NAMES_FAIL: 'GET_NAMES_FAIL',
    DELETE_NAME_START: 'DELETE_NAME_START',
    DELETE_NAME_SUCCESS: 'DELETE_NAME_SUCCESS',
    DELETE_NAME_FAIL: 'DELETE_NAME_FAIL',
    ADD_NAME: 'ADD_NAME',
  },
  categoryActions: {
    GET_CATEGORIES_START: 'GET_CATEGORIES_START',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAIL: 'GET_CATEGORIES_FAIL',
  },
};

export default actionTypes;
